---

version: '3.5'

services:
  minecraft-server:
    build: .
    ports:
    - 25565:25565
    container_name: minecraft-server
    restart: unless-stopped
    environment:
    - APP_UID=4321
    - APP_GID=4321
    - APP_MEMORY=8192M
    volumes:
    - /srv/minecraft-data:/minecraft-data

...

